name: Project Tests
on: 
  push:
    branches:
      - develop
      - pytest

  pull_request:
    branches:
      - develop
      - pytest

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with: 
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with PyTest
        run: pytest -v